### ISSUE TITLE
`@metadata` field contents not included in clones of event

### ISSUE THREAD

**Issue by magnusbaeck** [logstash-plugins/logstash-filter-split#11]
When cloning the original event the `@metadata` fields aren't included in the new events. I think users have good reasons to expect `@metadata` fields to tag along, especially given what the documentation says,

> The end result of each split is a complete copy of the event with only the current split section of the given field changed.

and as https://discuss.elastic.co/t/logstash-not-writing-to-elasticsearch-if-split-filter-is-used/43693 shows this can result in very surprising behavior.

**Comment by wiibaa** [comment]
Root issue is registered against logstash-core => https://github.com/elastic/logstash/issues/4306

**Comment by suyograo** [comment]
This will be available in 2.3 release of LS. As @wiibaa pointed out, the correct fix is in #4306

**Comment by magnusbaeck** [comment]
Well, if this is being fixed in Logstash core and we don't to work around the limitation in this plugin I'll close this issue.
