### ISSUE TITLE
may cause "java heap space" error

### ISSUE THREAD

**Issue by mzh2008** [logstash-plugins/logstash-filter-split#30]
Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash. {"exception"=>"Java heap space", "backtrace"=>["org.logstash.bivalues.BiValues$BiValueType$1.build(BiValues.java:109)", "org.logstash.bivalues.BiValues.build(BiValues.java:81)", "org.logstash.bivalues.BiValues.newBiValue(BiValues.java:89)", "org.logstash.ConvertedMap.newFromMap(ConvertedMap.java:30)", "org.logstash.Valuefier.convert(Valuefier.java:69)", "org.logstash.ConvertedList.newFromList(ConvertedList.java:34)", "org.logstash.Valuefier.convert(Valuefier.java:72)", "org.logstash.ConvertedMap.newFromMap(ConvertedMap.java:31)", "org.logstash.Valuefier.convert(Valuefier.java:69)", "org.logstash.Event.<init>(Event.java:62)", "org.logstash.Event.clone(Event.java:299)", "org.logstash.ext.JrubyEventExtLibrary$RubyEvent.ruby_clone(JrubyEventExtLibrary.java:169)", "org.logstash.ext.JrubyEventExtLibrary$RubyEvent$INVOKER$i$0$0$ruby_clone.call(JrubyEventExtLibrary$RubyEvent$INVOKER$i$0$0$ruby_clone.gen)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:134)", "rubyjit.LogStash::Filters::Split$$filter_0423715681c857d6c199c2676ccb1f954d7e56631975012498.block_0$RUBY$__file__(/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-split-3.1.3/lib/logstash/filters/split.rb:91)", "rubyjit$LogStash::Filters::Split$$filter_0423715681c857d6c199c2676ccb1f954d7e56631975012498$block_0$RUBY$__file__.call(rubyjit$LogStash::Filters::Split$$filter_0423715681c857d6c199c2676ccb1f954d7e56631975012498$block_0$RUBY$__file__)", "org.jruby.runtime.CompiledBlock19.yield(CompiledBlock19.java:135)", "org.jruby.runtime.Block.yield(Block.java:142)", "org.jruby.RubyArray.eachCommon(RubyArray.java:1606)", "org.jruby.RubyArray.each(RubyArray.java:1613)", "org.jruby.RubyArray$INVOKER$i$0$0$each.call(RubyArray$INVOKER$i$0$0$each.gen)", "org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:143)", "org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:154)", "rubyjit.LogStash::Filters::Split$$filter_0423715681c857d6c199c2676ccb1f954d7e56631975012498.__file__(/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-split-3.1.3/lib/logstash/filters/split.rb:88)", "rubyjit.LogStash::Filters::Split$$filter_0423715681c857d6c199c2676ccb1f954d7e56631975012498.__file__(/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-split-3.1.3/lib/logstash/filters/split.rb)", "org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:201)", "org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:177)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:183)", "rubyjit.LogStash::Filters::Base$$do_filter_8e8403dcfdf01a35ffca12ed35ec4e79455489071975012498.__file__(/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:145)", "rubyjit.LogStash::Filters::Base$$do_filter_8e8403dcfdf01a35ffca12ed35ec4e79455489071975012498.__file__(/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb)", "org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:201)", "org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:177)"]}

- Version:
- Operating System:Linux version 4.9.43-17.38.amzn1.x86_64 (mockbuild@gobi-build-60008) (gcc version 4.8.3 20140911 (Red Hat 4.8.3-9) (GCC) )
- Config File (if you have sensitive info, please remove it): 
  input {
 elasticsearch {
  hosts => "qa.audienceanywhere.com:9989"
  index => "aa"
 size => 500
scroll =>"5m"
  query => '{"query": {
     "bool": {
             "must": [
                   {
                      "term": {
                              "state":"CA"
                                  }
                    },{
                            "nested": {
                                    "path": "emails",
                                        "query": {
                                             "terms": {
                                                      "emails.email_active_code": ["A", "B", "C", "Z"]
                                                         }
                                            }
                                        }
                                }
                          ]
                         }
         }}'
  }
}

filter {

    split {
        field => "emails"
        target=> "emailJson"
        terminator=>","
        periodic_flush =>true
    }

}

output {
     csv {
      fields => ["individual_id", "first_name", "last_name","address1","address2","city","state","zip","emailJson"]
      path => "/usr/share/logstash/test/data/datam_split6.csv"
     }
}
- Sample Data: the query data is about 10,000,000 records
- Steps to Reproduce: run logstash with the config file

**Comment by colinsurprenant** [comment]
Thanks @mzh2008 for reporting this.
Similar to #35 - closing. Feel free to reopen if #35 does not clarify.
