### ISSUE TITLE
./logstash-plugin install logstash-filter-mutate

### ISSUE THREAD

**Issue by fanyoujian** [logstash-plugins/logstash-filter-split#32]
logstash 5.5.3
An error occurred while installing logstash-core-event-java (5.2.2), and Bundler cannot continue

when gem install logstash-core-event-java -v '5.2.2', other error occurred  Could not find a valid gem 'logstash-core-event-java' (= 5.2.2) in any repository

**Comment by colinsurprenant** [comment]
Thanks for reporting @fanyoujian - this is really outdated now and we haven't had other reports of a similar problem so I will close. Please feel free to reopen if this is still a problem.
