### ISSUE TITLE
OOM issue

### ISSUE THREAD

**Issue by TheFausap** [logstash-plugins/logstash-filter-split#35]
Hello,
after upgrading to Logstash 6.4.2, I'm getting these OOM errors when running the pipeline:

```
[2018-10-24T12:57:08,983][ERROR][logstash.pipeline        ] Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash. {:pipeline_id=>"main", "exception"=>"Java heap space", "backtrace"=>["org.jruby.util.ByteList.<init>(ByteList.java:91)", "org.jruby.util.ByteList.dup(ByteList.java:325)", "org.jruby.util.ByteList.dup(ByteList.java:297)", "org.jruby.RubyString.doClone(RubyString.java:1309)", "org.logstash.Cloner.deep(Cloner.java:25)", "org.logstash.Cloner.deepMap(Cloner.java:65)", "org.logstash.Cloner.deep(Cloner.java:21)", "org.logstash.Event.clone(Event.java:268)", "org.logstash.ext.JrubyEventExtLibrary$RubyEvent.rubyClone(JrubyEventExtLibrary.java:147)", "org.logstash.ext.JrubyEventExtLibrary$RubyEvent.rubyClone(JrubyEventExtLibrary.java:142)", "java.lang.invoke.LambdaForm$DMH/2065857933.invokeSpecial_LL_L(LambdaForm$DMH)", "java.lang.invoke.LambdaForm$BMH/229581552.reinvoke(LambdaForm$BMH)", "java.lang.invoke.LambdaForm$MH/1826699684.delegate(LambdaForm$MH)", "java.lang.invoke.LambdaForm$MH/840737335.guard(LambdaForm$MH)", "java.lang.invoke.LambdaForm$MH/1826699684.delegate(LambdaForm$MH)", "java.lang.invoke.LambdaForm$MH/840737335.guard(LambdaForm$MH)", "java.lang.invoke.LambdaForm$MH/944826636.linkToCallSite(LambdaForm$MH)", "usr.share.logstash.vendor.bundle.jruby.$2_dot_3_dot_0.gems.logstash_minus_filter_minus_split_minus_3_dot_1_dot_6.lib.logstash.filters.split.RUBY$block$filter$1(/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-filter-split-3.1.6/lib/logstash/filters/split.rb:91)", "java.lang.invoke.LambdaForm$DMH/1812251945.invokeStatic_L8_L(LambdaForm$DMH)", "java.lang.invoke.LambdaForm$MH/925410680.invokeExact_MT(LambdaForm$MH)", "org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:156)", "org.jruby.runtime.BlockBody.yield(BlockBody.java:114)", "org.jruby.runtime.Block.yield(Block.java:165)", "org.jruby.RubyArray.each(RubyArray.java:1734)", "org.jruby.RubyArray$INVOKER$i$0$0$each.call(RubyArray$INVOKER$i$0$0$each.gen)", "org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroBlock.call(JavaMethod.java:498)", "org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:145)", "java.lang.invoke.LambdaForm$DMH/1523683407.invokeVirtual_L6_L(LambdaForm$DMH)", "java.lang.invoke.LambdaForm$BMH/497877502.reinvoke(LambdaForm$BMH)", "java.lang.invoke.LambdaForm$MH/254416915.linkToCallSite(LambdaForm$MH)", "usr.share.logstash.vendor.bundle.jruby.$2_dot_3_dot_0.gems.logstash_minus_filter_minus_split_minus_3_dot_1_dot_6.lib.logstash.filters.split.RUBY$method$filter$0(/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-filter-split-3.1.6/lib/logstash/filters/split.rb:88)", "usr.share.logstash.vendor.bundle.jruby.$2_dot_3_dot_0.gems.logstash_minus_filter_minus_split_minus_3_dot_1_dot_6.lib.logstash.filters.split.RUBY$method$filter$0$__VARARGS__(/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-filter-split-3.1.6/lib/logstash/filters/split.rb)"], :thread=>"#<Thread:0x704ac961 sleep>"}
[2018-10-24T12:57:09,076][ERROR][org.logstash.Logstash    ] java.lang.OutOfMemoryError: Java heap space

```
It seems the problem is in the split filter. 
I'm using a JAVA heap size of 4GB and my OS is Centos 7.5.1804 (running in a vm)
The server has 4 vCPU and 16GB RAM

The logstash configuration is:

```
# ------------ Pipeline Settings --------------
#
# The ID of the pipeline.
#
# pipeline.id: main
#
# Set the number of workers that will, in parallel, execute the filters+outputs
# stage of the pipeline.
#
# This defaults to the number of the host's CPU cores.
#
pipeline.workers: 8
#
# How many events to retrieve from inputs before sending to filters+workers
#
pipeline.batch.size: 500
#
# How long to wait in milliseconds while polling for the next event
# before dispatching an undersized batch to filters+outputs
#
pipeline.batch.delay: 5
```
and

```
# ------------ Queuing Settings --------------
#
# Internal queuing model, "memory" for legacy in-memory based queuing and
# "persisted" for disk-based acked queueing. Defaults is memory
#
queue.type: persisted
#
# If using queue.type: persisted, the directory path where the data files will be stored.
# Default is path.data/queue
#
# path.queue:
#
# If using queue.type: persisted, the page data files size. The queue data consists of
# append-only data files separated into pages. Default is 64mb
#
queue.page_capacity: 128mb
#
# If using queue.type: persisted, the maximum number of unread events in the queue.
# Default is 0 (unlimited)
#
# queue.max_events: 0
#
# If using queue.type: persisted, the total capacity of the queue in number of bytes.
# If you would like more unacked events to be buffered in Logstash, you can increase the
# capacity using this setting. Please make sure your disk drive has capacity greater than
# the size specified here. If both max_bytes and max_events are specified, Logstash will pick
# whichever criteria is reached first
# Default is 1024mb or 1gb
#
queue.max_bytes: 4096mb
```

the pipeline is configured in this way:

```
input {
    http_poller {
        urls => {
            test1 => {
                # Supports all options supported by ruby's Manticore HTTP client
                tags => ["webservices"]
                method => get
                url => "https://srv1/rest/management/dashboard/B1webservices"
                auth => {
                    user => "X"
                    password => "Y"
                }
                verify_cert => false
            }
            test2 => {
                # Supports all options supported by ruby's Manticore HTTP client
                tags => ["webservices"]
                method => get
                url => "https://srv1/rest/management/dashboard/B2webservices"
                auth => {
                    user => "X"
                    password => "Y"
                }
                verify_cert => false
            }
            test3 => {
                # Supports all options supported by ruby's Manticore HTTP client
                tags => ["webrequests"]
                method => get
                url => "https://srv1/rest/management/dashboard/B1webrequests"
                auth => {
                    user => "X"
                    password => "Y"
                }
                verify_cert => false
            }
            test4 => {
                # Supports all options supported by ruby's Manticore HTTP client
                tags => ["webrequests"]
                method => get
                url => "https://srv1/rest/management/dashboard/B2webrequests"
                auth => {
                    user => "X"
                    password => "Y"
                }
                verify_cert => false
            }

        }
        request_timeout => 14400
        connect_timeout => 4000
        socket_timeout => 4000
        # Supports "cron", "every", "at" and "in" schedules by rufus scheduler
        schedule => { "every" => "6m"}
        truststore => "/home/OPS/myTrustStore.jks"
        truststore_password => "XX"
        automatic_retries => 3
        codec => "plain"
        # A hash of request metadata info (timing, response headers, etc.) will be sent here
        metadata_target => "http_poller_metadata"
    }
}

filter {
  if [http_poller_metadata][code] == 200 {
    if "webservices" in [http_poller_metadata][request][tags] {
       xml {
               remove_namespaces => true
               source => "message"
               store_xml => false
               xpath => [
                       "//dashboardreport/@reportdate", "time",
                       "//webservice", "webservice",
                       "//source/@name", "source_d"
               ]
       }
       split {
           field => "webservice"
       }
    }
    if "webrequests" in [http_poller_metadata][request][tags] {
       xml {
               remove_namespaces => true
               source => "message"
               store_xml => false
               xpath => [
                       "//dashboardreport/@reportdate", "time",
                       "//webrequest", "webrequest",
                       "//source/@name", "source_d"
               ]
       }
       split {
           field => "webrequest"
       }
    }
  }
}

output {
 if [http_poller_metadata][code] == 200 {
   if [http_poller_metadata][name] == "test1" or [http_poller_metadata][name] == "test2" {
      file {
          path => "/home/OPS/dyna_ws.log"
          codec => line { format => "%{time} %{webservice} market=%{source_d}" }
      }
   }
   if [http_poller_metadata][name] == "test3" or [http_poller_metadata][name] == "test4" {
      file {
          path => "/home/OPS/dyna_wr.log"
          codec => line { format => "%{time} %{webrequest} market=%{source_d}" }
      }
   }
 }
}

```
The webservices table in the XML has about 40 rows and webrequests table has about 100 rows.

**Comment by TheFausap** [comment]
I removed the webrequests part (the bigger) and the OOM error disappear.
Is there a way to perform some tuning of this plugin ?

**Comment by rguptai** [comment]
Hi

I  have encountered the same issue after upgrading from 5.5 to 6.5.2. We are using Split filter only at 1 place in our configuration. Is there any workaround/solution for this issue yet?

 Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash. {:pipeline_id=>"main", "exception"=>"Java heap space", "backtrace"=>["org.jruby.util.ByteList.<init>(ByteList.java:91)", "org.jruby.util.ByteList.dup(ByteList.java:325)", "org.jruby.util.ByteList.dup(ByteList.java:297)", "org.jruby.RubyString.doClone(RubyString.java:1309)", "org.logstash.Cloner.deep(Cloner.java:25)", "org.logstash.Cloner.deepMap(Cloner.java:65)", "org.logstash.Cloner.deep(Cloner.java:21)", "org.logstash.Event.clone(Event.java:268)", "org.logstash.ext.JrubyEventExtLibrary$RubyEvent.rubyClone(JrubyEventExtLibrary.java:147)", "org.logstash.ext.JrubyEventExtLibrary$RubyEvent.rubyClone(JrubyEventExtLibrary.java:142)", "java.lang.invoke.LambdaForm$DMH/1157726741.invokeSpecial_LL_L(LambdaForm$DMH)", "java.lang.invoke.LambdaForm$BMH/251074782.reinvoke(LambdaForm$BMH)", "java.lang.invoke.LambdaForm$MH/769429195.delegate(LambdaForm$MH)", "java.lang.invoke.LambdaForm$MH/422882684.guard(LambdaForm$MH)", "java.lang.invoke.LambdaForm$MH/769429195.delegate(LambdaForm$MH)", "java.lang.invoke.LambdaForm$MH/422882684.guard(LambdaForm$MH)", "java.lang.invoke.LambdaForm$MH/706960270.linkToCallSite(LambdaForm$MH)", "docs.root.logstash.logstash.vendor.bundle.jruby.$2_dot_3_dot_0.gems.logstash_minus_filter_minus_split_minus_3_dot_1_dot_6.lib.logstash.filters.split.RUBY$block$filter$1(/docs/root/logstash/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-filter-split-3.1.6/lib/logstash/filters/split.rb:91)", "java.lang.invoke.LambdaForm$DMH/600728936.invokeStatic_L8_L(LambdaForm$DMH)", "java.lang.invoke.LambdaForm$MH/2124562732.invokeExact_MT(LambdaForm$MH)", "org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:156)", "org.jruby.runtime.BlockBody.yield(BlockBody.java:114)", "org.jruby.runtime.Block.yield(Block.java:165)", "org.jruby.RubyArray.each(RubyArray.java:1734)", "org.jruby.RubyArray$INVOKER$i$0$0$each.call(RubyArray$INVOKER$i$0$0$each.gen)", "org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroBlock.call(JavaMethod.java:498)", "org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:145)", "java.lang.invoke.LambdaForm$DMH/840008200.invokeVirtual_L6_L(LambdaForm$DMH)", "java.lang.invoke.LambdaForm$BMH/2134194703.reinvoke(LambdaForm$BMH)", "java.lang.invoke.LambdaForm$MH/86384329.linkToCallSite(LambdaForm$MH)", "docs.root.logstash.logstash.vendor.bundle.jruby.$2_dot_3_dot_0.gems.logstash_minus_filter_minus_split_minus_3_dot_1_dot_6.lib.logstash.filters.split.RUBY$method$filter$0(/docs/root/logstash/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-filter-split-3.1.6/lib/logstash/filters/split.rb:88)", "docs.root.logstash.logstash.vendor.bundle.jruby.$2_dot_3_dot_0.gems.logstash_minus_filter_minus_split_minus_3_dot_1_dot_6.lib.logstash.filters.split.RUBY$method$filter$0$__VARARGS__(/docs/root/logstash/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-filter-split-3.1.6/lib/logstash/filters/split.rb)"], :thread=>"#<Thread:0x321be35f sleep>"}
[2018-12-26T11:07:22,938][ERROR][org.logstash.Logstash    ] java.lang.OutOfMemoryError: Java heap space

**Comment by colinsurprenant** [comment]
@TheFausap @rguptai The reported OOM obviously indicates that something is blowing up in memory. The way the split filter works is to create a new cloned event from the original event for each split part of the configured source field. This means that if a given event will generate, say, 10 split parts, the original event will be cloned 10 times. Now if you take into account that filters are applied on batches which are held in memory, with a batch size of 500, this means that if each event is split into 10 events,  the in-memory batch will grow to 5000 events.  If these original event contain "large" documents we can see how this can blow up.

For now I think a potential workaround would be to reduce the batch size. Other ideas would be to use the mutate filter to remove unnecessary fields? 

Let me know if this is helpful.

**Comment by rguptai** [comment]
@colinsurprenant our current configuration with split filter has been working with Logstash 6.0.1 without any issues. This issue started occurring only after we upgraded to 6.5.2 (with same data load). Based on your comment, 1 possible explanation is that default batch size has been increases in 6.5.2. I'll check for that. Not sure if anything has been changed in filter itself between 6.0.1 and 6.5.2?

**Comment by colinsurprenant** [comment]
@rguptai nothing in the filter has changed between LS 6.0.1 (split filter v3.1.5) and LS 6.5.2 (split filter v3.1.6) that could explain this behaviour. Also nothing has changed in terms of default `pipeline.workers` (defaults to the number of CPU cores) or `pipeline.batch.size` (default at 125). 

Further investigating, I see that in 6.3.0 [a bug was fixed](https://github.com/elastic/logstash/pull/9653) on the string values cloning. In summary, before 6.3 string were actually not cloned and the same object was passed around in the cloned events but now a *proper* cloning is done which would definitely explain the significant increase of memory requirement when cloning events with large strings such as XML documents.

**Comment by colinsurprenant** [comment]
@rguptai As I said, the bug had the *positive* side effect of using less memory per cloned event, but that bug was also the cause of other problems and now that it is fixed, a properly cloned event takes more memory. At this point you have these options:
- increase the node heap
- reduce the batch size
- add a pre "cleanup" filter(s) (mutate) which will prune unnecessary fields out of the event
 before the cloning operation

**Comment by rguptai** [comment]
Thanks @colinsurprenant . This was really helpful. I'll try some of these options.

**Comment by colinsurprenant** [comment]
@rguptai you're welcome - please followup and et us know how this is working out for you.

**Comment by yaauie** [comment]
It looks like this issue has gone stale after suggestions were offered. I'm closing it out, but feel free to re-open if it is still an issue.
