### ISSUE TITLE
split filter bailing on length == 1 should be configurable

### ISSUE THREAD

**Issue by mmastrac** [logstash-plugins/logstash-filter-split#5]
Ideally the logic of whether split bails on length == 1 should be configurable. We have an event source that returns 0..N items in an array. In our case the split filter should output 0..N events from this, but ensure that any results are properly unwrapped from the array (and further add_field/remove_field calls happen) regardless of the number of items we receive.

```
    # Skip filtering if splitting this event resulted in only one thing found.
    return if splits.length == 1
```

**Comment by pall-valmundsson** [comment]
Just hit the same issue. Ended up creating a ruby filter that replaces the field with array element 0 if the array length == 1.

**Comment by jordansissel** [comment]
Can y'all help me understand what oyu want? What would be the result of a split where nothing was split? Add fields? Could you add fields in a mutate _after_ the thing?

**Comment by jordansissel** [comment]
(I agree maybe we could make this configurable, or delete that line of code entirely, I Just want to understand more what you're needing so that whatever change is made will suit your needs :)

**Comment by mmastrac** [comment]
I think it makes the most sense to emit nothing in the case where the array is length 0 and treat an array of length 1 as a degenerate case of length > 1. 

This is what I'd expect if I were using this to split from a source that returns a variable number of items in an array, where I don't know what the number of items would be ahead of time.

**Comment by pall-valmundsson** [comment]
Looking at the code again made me realize what's wrong. The `splits.length == 1` makes sense if you have a string: just leave it as it is. But if you have an array to split that has `.length == 1` doing nothing will leave the field as an array while `.length > 1` will actually make the field a non array field with the values from each array element. Differing results for array length=1 vs length>1.

So a solution could be to change `return if splits.length == 1` to `return if splits.length == 1 && original_value.is_a?(String)`. Removing the line is also a solution but at the expense of always cloning the event.

**Comment by mmastrac** [comment]
I would bet that there are unexpected side-effects of returning early regardless, even for a string: users like myself might be expecting add_field/remove_field to trigger for records that don't split. This appears not to happen in the case of early return.

I'd personally recommend just removing that line entirely as (I believe) the behavior is surprising in many cases.

I'm definitely new to logstash so I might have missed something, but it felt surprising (and took a lot of digging into the source to figure out what was happening).

**Comment by rdenniston** [comment]
I ran into this issue myself, with an array split, it causes issues if the array length is one, to keep in line with the intent for strings, and special handling for arrays, I moved the test for length into their respective places. If array, it checks that the length is greater than 0. If string, nothing has changed. I can do a pull request if you would like to see what I did.

**Comment by papile** [comment]
This was also confusing for me, and I spent a long time thinking I had a filter syntax problem. I am handling arrays that can have 1..n items in them. The return for a String may make sense but even then it does not as it should not short circuit as in the case that @mmastrac mentioned. People may be using this to iterate. In Ruby the pattern is to iterate even on empty arrays so I do not see why this should return early.

Regardless in the Array case it is definitely broken as users using this would be expecting to iterate the array and return the events with that field made into a single enumerated object. Leaving it still in the array form is broken. I would argue even with 0 events, the field should be nil then.

So +1 to removing this early return completely.

**Comment by msassak** [comment]
I just ran into this myself when splitting an array. It's very surprising behavior. I agree that the early return should be removed completely, and arrays should be split regardless of length.

**Comment by erlichmen** [comment]
I think this issue is resolved, code now is:
`return if splits.length == 1 && original_value.is_a?(String)`

**Comment by wiibaa** [comment]
Issue resolved by https://github.com/logstash-plugins/logstash-filter-split/commit/87144263ac2c2ab7192bf50dcf70784caa04bbd3

@suyograo can you close please

**Comment by ph** [comment]
closed by https://github.com/logstash-plugins/logstash-filter-split/commit/87144263ac2c2ab7192bf50dcf70784caa04bbd3
