### ISSUE TITLE
Update documentation of reflect that an array of objects will be split as well

### ISSUE THREAD

**Issue by elssar** [logstash-plugins/logstash-filter-split#9]
Currently the documentation reads like only strings can be split into multiple events. But the code seems to suggest that an array of objects can be split into multiple events as well.

That is, I can use the filter to split both

```
[{a:1, b:2}
{a:2, b:3}]

// and
"{\"a\":1, \"b\":2},
\"a\":2, \"b\":2}"
```

into the same two events. From the documentation it isn't clear

**Comment by suyograo** [comment]
Fixed in https://github.com/logstash-plugins/logstash-filter-split/pull/12
